### ISSUE TITLE
open OMN file

### ISSUE THREAD

**Issue by rovinsan** [MarcelRobeer/VisualNarrator#10]
How to open OMN file in protege? is it possible to open OMN file in protege?

**Comment by MarcelRobeer** [comment]
.omn files (Manchester OWL Syntax; [https://www.w3.org/TR/owl2-manchester-syntax/](https://www.w3.org/TR/owl2-manchester-syntax/)) should be openable in Protégé. Otherwise I recommend using [WebVOWL](vowl.visualdataweb.org/webvowl.html).
