### ISSUE TITLE
Arguments and Usage method

### ISSUE THREAD

**Issue by usmanksri123** [MarcelRobeer/VisualNarrator#20]
Please guide me that what is the usage method or command with arguments? Tried many times but showing errors.  I've installed libraries according to recommendations. Please help me, im new in python.
![1](https://user-images.githubusercontent.com/92269067/136707189-933e600b-defe-4744-84c9-39bcfa318bcb.PNG)
![2](https://user-images.githubusercontent.com/92269067/136707191-5c18c187-f452-4a15-8600-a18d4c43d8b4.PNG)
![cmd](https://user-images.githubusercontent.com/92269067/136707193-a7af34ac-0a62-4c37-b58b-b1b48d9839de.PNG)

**Comment by MarcelRobeer** [comment]
Which verison of Python does it show when you try `python --version` and `python3 --version`?

*Edit*: looks like you are trying to run the file `visualn.py` which included the line `python run.py ...`. You can type in `python run.py ...` directly into the terminal.

**Comment by usmanksri123** [comment]
My python versions was 3.6.13 and language model 'en_core_web_md' was missed in my environment, fixed both. Now the code is running. 
Thank you very much.
