### ISSUE TITLE
Want to use Stanford CoreNLP library for Java to extract conceptual models from user stories

### ISSUE THREAD

**Issue by ghost** [MarcelRobeer/VisualNarrator#9]
I need some help to extract conceptual models from user stories using Stanford CoreNLP library for java.

**Comment by MarcelRobeer** [comment]
Visual Narrator was implemented in Python using NLP toolkit spaCy. You could look into https://stanfordnlp.github.io/CoreNLP/other-languages.html as it provides Python implementations for Standford CoreNLP. If you want to implement it in Java please refer to Algorithm 1 in our publication 'Automated Extraction of Conceptual Models from User Stories via NLP'.
